### ISSUE TITLE
Please add this to the guide

### ISSUE THREAD

**Issue by ekalchev** [JoanComasFdz/dotnet-how-to-debug-source-generator-vs2022#1]
Please add this to the guide because took me too much time to figure out why Roslyn Analyzer was missing as options 

"Also make sure in the Visual Studio Installer that you have installed the .NET Compiler Platform SDK."

**Comment by JoanComasFdz** [comment]
Interestingly, I actually wrote it in the stackoverflow question: https://stackoverflow.com/questions/70774200/how-to-debug-roslyn-source-generator-in-vs-2022/71314452#71314452.
I am updating it now
